//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\hcump\source\repos\SuperB\SuperB\SuperB.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SuperB {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SuperBParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public interface ISuperBVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>Parenthesizedl</c>
	/// labeled alternative in <see cref="SuperBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedl([NotNull] SuperBParser.ParenthesizedlContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Unparenthesized</c>
	/// labeled alternative in <see cref="SuperBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnparenthesized([NotNull] SuperBParser.UnparenthesizedContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Procheader</c>
	/// labeled alternative in <see cref="SuperBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcheader([NotNull] SuperBParser.ProcheaderContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Funcheader</c>
	/// labeled alternative in <see cref="SuperBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncheader([NotNull] SuperBParser.FuncheaderContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] SuperBParser.NotContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryAdditive</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryAdditive([NotNull] SuperBParser.UnaryAdditiveContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Ident</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdent([NotNull] SuperBParser.IdentContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Instr</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstr([NotNull] SuperBParser.InstrContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Parenthesized</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized([NotNull] SuperBParser.ParenthesizedContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Literal</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] SuperBParser.LiteralContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Binary</c>
	/// labeled alternative in <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary([NotNull] SuperBParser.BinaryContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Loc</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc([NotNull] SuperBParser.LocContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Longselect</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongselect([NotNull] SuperBParser.LongselectContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Exitstmt</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitstmt([NotNull] SuperBParser.ExitstmtContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Func</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] SuperBParser.FuncContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Reference</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] SuperBParser.ReferenceContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Dim</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDim([NotNull] SuperBParser.DimContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Longfor</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongfor([NotNull] SuperBParser.LongforContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Proc</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProc([NotNull] SuperBParser.ProcContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] SuperBParser.AssignmentContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Onselect</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnselect([NotNull] SuperBParser.OnselectContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Shortif</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortif([NotNull] SuperBParser.ShortifContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Longif</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongif([NotNull] SuperBParser.LongifContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>IdentifierOnly</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierOnly([NotNull] SuperBParser.IdentifierOnlyContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Shortrepeat</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortrepeat([NotNull] SuperBParser.ShortrepeatContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Implicit</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicit([NotNull] SuperBParser.ImplicitContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Shortfor</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortfor([NotNull] SuperBParser.ShortforContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>Longrepeat</c>
	/// labeled alternative in <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongrepeat([NotNull] SuperBParser.LongrepeatContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SuperBParser.ProgramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] SuperBParser.LineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.stmtlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtlist([NotNull] SuperBParser.StmtlistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.constexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstexpr([NotNull] SuperBParser.ConstexprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.rangeexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeexpr([NotNull] SuperBParser.RangeexprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] SuperBParser.StmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.prochdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProchdr([NotNull] SuperBParser.ProchdrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.funchdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunchdr([NotNull] SuperBParser.FunchdrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SuperBParser.IdentifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.parenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedlist([NotNull] SuperBParser.ParenthesizedlistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.unparenthesizedlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnparenthesizedlist([NotNull] SuperBParser.UnparenthesizedlistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparator([NotNull] SuperBParser.SeparatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SuperBParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] SuperBParser.ExprContext context);
}
} // namespace SuperB
